---
title: "Cross Validation"
author: "Vanessa Dinh"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(modelr)
library(mgcv)
```

## Step One

```{r}
nonlin_df = 
  tibble(
    id = 1:100,
    x = runif(100, 0, 1),
    y = 1 - 10 * (x - .3) ^ 2 + rnorm(100, 0, .3)
  )

nonlin_df %>% 
  ggplot(aes(x = x, y = y)) + 
  geom_point()
```

Let's get this by hand. Making Training and Testing datasets for model selection.

```{r}
train_df = sample_n(nonlin_df, 80)
test_df = anti_join(nonlin_df, train_df, by = "id") 
#anti_join, codes for what is not in the training dataframe
```

```{r}
ggplot(train_df, aes(x = x, y = y)) + 
  geom_point() + 
  geom_point(data = test_df, color = "red")
```

Let's try to fit htree models.

```{r}
linear_mod = lm(y ~ x, data = train_df)
smooth_mod = mgcv::gam(y ~ s(x), data = train_df)
wiggly_mod = mgcv::gam(y ~ s(x, k = 30), sp = 10e-6, data = train_df)
```

Let's see the results.

```{r}
train_df %>% 
  add_predictions(wiggly_mod) %>% 
  ggplot(aes(x = x, y = y)) +
  geom_point() +
  geom_line(aes(y = pred), color = "red")
```
Wiggly is too complex while linear is too simple and not a good predictor. Use cross validation to confirm.

Let's make predictions and compute Root Mean Squared Errors.

```{r}
test_df %>% add_predictions(linear_mod) #long way

rmse(linear_mod, test_df) #easier way
rmse(smooth_mod, test_df)
rmse(wiggly_mod, test_df)

#prediction error, lower is more accurate
```

## Can we iterate ...?

```{r}
cv_df =
  crossv_mc(nonlin_df, 100) %>% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)
  ) %>% 
  mutate(
    linear_fits = map(.x = train, ~lm(y ~ x, data = .x))
  )


```

