---
title: "Linear Models"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)

set.seed(1)
```

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) %>% 
  filter(borough != "Staten Island") %>% 
  select(price, stars, borough, neighborhood, room_type)
```

## Fit the first model
```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)
fit

summary(fit)

fit %>% 
  broom::tidy() %>% 
  mutate(
    term = str_replace(term, "borough", "Borough: ")
  ) %>% 
  select(term, estimate, p.value) %>% 
  knitr::kable(digits = 2)

```

Let's change reference category.

```{r}
fit =
  nyc_airbnb %>% 
  mutate(
    borough = fct_infreq(borough)
  )%>% 
  lm(price ~ stars + borough, data = .)
  
  
fit %>% 
  broom::tidy() %>% 
  mutate(
    term = str_replace(term, "borough", "Borough: ")
  ) %>% 
  select(term, estimate, p.value) %>% 
  knitr::kable(digits = 2)

fit %>% 
  broom::glance() %>% 
  select(AIC)
```
## Diagnostics

```{r}
modelr::add_residuals(nyc_airbnb, fit) %>% 
  ggplot(aes(x = stars, y = resid)) +
  geom_point()

nyc_airbnb %>% 
  modelr::add_residuals(fit) %>% 
  ggplot(aes(x = borough, y = resid)) +
  geom_violin() +
  ylim(-250, 250)
```

## Hypothesis Testing

one coefficient (let's say 'stars')

```{r}
fit %>% 
  broom::tidy()

fit_null = lm(price ~ stars, data = nyc_airbnb)
fit_alt = lm(price ~ stars + borough, data = nyc_airbnb)

anova(fit_null, fit_alt) %>% 
  broom::tidy()
```

## Room Type by borough

Interactions ...?

```{r}
fit =
  nyc_airbnb %>% 
  lm(price ~ stars + borough * room_type, data = .)

fit %>% 
  broom::tidy()
```

So... can we fit models by borough...?

```{r}
nyc_airbnb %>%
  nest(df = -borough) %>% 
  mutate(
    models = map(.x = df, ~lm(price ~ stars + room_type, data = .x))
  ) %>% 
  pull(models)

nyc_airbnb %>%
  nest(df = -borough) %>% 
  mutate(
    models = map(.x = df, ~lm(price ~ stars + room_type, data = .x)),
    results = map(models, broom::tidy)
  ) %>% 
  select(-df, -models) %>% 
  unnest(results)

# #nyc_airbnb %>% 
#   select(borough, term, estimate) %>% 
#   mutate(term = fct_inorder(term)) %>% 
#   pivot_wider(
#     names_from = term, values_from = estimate) %>% 
#   knitr::kable(digits = 3)
```

testing without map, double check

```{r}
nyc_airbnb %>% 
  filter(borough == "Bronx") %>% 
  lm(price ~ stars + room_type, data = .) %>% 
  broom::tidy()
```

